# Generated by Django 5.1.7 on 2025-03-30 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='trainee',
            field=models.ForeignKey(limit_choices_to={'role': 'trainee'}, on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workout',
            name='trainers',
            field=models.ManyToManyField(limit_choices_to={'role': 'trainer'}, related_name='assigned_workouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
